FROM continuumio/miniconda3
RUN apt-get update
RUN apt-get install -y python-dev graphviz libgraphviz-dev pkg-config
RUN conda install python=2.7
RUN conda install -c anaconda pygraphviz
#RUN pip install trilearn    
